### ISSUE TITLE
Wifi and Telephony permission denied

### ISSUE THREAD

**Issue by juancamilo87** [denzilferreira/aware-plugin-template#1]
Hi,
I'm developing a plugin for Aware, and whenever I try to turn Telephony on using Aware_Preferences.STATUS_TELEPHONY I get the following error.

>27126-27126/com.aware.plugin.template E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.aware.plugin.template, PID: 27126
    java.lang.RuntimeException: Unable to create service com.aware.Telephony: java.lang.SecurityException: Neither user 10299 nor current process has android.permission.ACCESS_COARSE_LOCATION.
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2741)
            at android.app.ActivityThread.access$1800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1361)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.SecurityException: Neither user 10299 nor current process has android.permission.ACCESS_COARSE_LOCATION.
            at android.os.Parcel.readException(Parcel.java:1540)
            at android.os.Parcel.readException(Parcel.java:1493)
            at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenForSubscriber(ITelephonyRegistry.java:483)
            at android.telephony.TelephonyManager.listen(TelephonyManager.java:2187)
            at com.aware.Telephony.onCreate(Telephony.java:110)
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2731)
            at android.app.ActivityThread.access$1800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1361)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

For Wifi is a similar error but with WIFI permissions.

**Comment by denzilferreira** [comment]
You’ll need to add the permissions your plugin needs to access that data, for example for the telephony:
<uses-permission android:name0=‘android.permission.ACCESS_COARSE_LOCATION’ />


Otherwise, the users wouldn’t know what kind of permissions a specific plugin needs. 
	Denzil;
